# Generated by Django 5.0.3 on 2026-03-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchamodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
